/* eslint-disable no-undef */
const express = require('express');
const storageImg = require('../multer/multer')
const adminController = require('../controller/admin-controller');
const sessionController = require('../middllewares/session-control')
const router = express.Router();

// GET METHODS

router.get('/',adminController.adminLogin)
router.get('/admin-dashboard',sessionController.adminSession,adminController.dashboard)
router.get('/logout',sessionController.adminSession,adminController.logout)
router.get('/admin-products',sessionController.adminSession,adminController.products)
router.get('/add-products',sessionController.adminSession,adminController.addproducts)
router.get('/edit-products/:id',sessionController.adminSession,adminController.editProducts)
router.get('/edit-category/:id',sessionController.adminSession,adminController.editCategory)
router.get('/edit-subcategory/:id',sessionController.adminSession,adminController.editsubCategory)
router.get('/edit-banner/:id',sessionController.adminSession,adminController.editBanner)
router.get('/edit-coupon/:id',sessionController.adminSession,adminController.editCoupon)
router.get('/edit-news/:id',sessionController.adminSession,adminController.editNews)
router.get('/admin-users',sessionController.adminSession,adminController.adminUsers)
router.get('/admin-banner',sessionController.adminSession,adminController.adminBanner)
router.get('/admin-sales',sessionController.adminSession,adminController.adminSales)
router.get('/add-banner',sessionController.adminSession,adminController.addBanner)
router.get('/latest-news',sessionController.adminSession,adminController.latestNews)
router.get('/admin-coupon',sessionController.adminSession,adminController.adminCoupon)
router.get('/add-coupon',sessionController.adminSession,adminController.addCoupon)
router.get('/add-news',sessionController.adminSession,adminController.addNews)
router.get('/admin-orders',sessionController.adminSession,adminController.adminOrders)
router.get('/view-order/:id',sessionController.adminSession,adminController.viewOrder)
router.get('/admin-category',sessionController.adminSession,adminController.adminCategory)
router.get('/admin-subcategory',sessionController.adminSession,adminController.adminSubcategory)
router.get('/delete-banner/:id',sessionController.adminSession,adminController.deleteBanner)
router.get('/delete-coupon/:id',sessionController.adminSession,adminController.deleteCoupon)
router.get('/delete-news/:id',sessionController.adminSession,adminController.deleteNews)

// POST METHODS

router.post('/admin-dashboard',adminController.doLogin)
router.post('/add-products',storageImg.uploadImages,storageImg.resizeImages, adminController.doaddproducts)
router.post('/edit-products/:id',storageImg.uploadImages,storageImg.resizeImages, adminController.doeditProducts)
router.post('/edit-category/:id', adminController.doeditCategory)
router.post('/edit-subcategory/:id', adminController.doeditSubCategory)
router.post('/edit-banner/:id',storageImg.uploadImages,storageImg.resizeImages, adminController.doEditBanner)
router.post('/edit-coupon/:id', adminController.doeditCoupon)
router.post('/productUnblock/:id',adminController.unblockProduct)
router.post('/productBlock/:id',adminController.blockProduct)
router.post('/userUnblock/:id',adminController.unblockUser)
router.post('/userBlock/:id',adminController.blockUser)
router.post('/add-coupon',adminController.doaddCoupon)
router.post('/add-category',adminController.addCategory)
router.post('/add-banner',storageImg.uploadImages,storageImg.resizeImages,adminController.doaddBanner)
router.post('/add-news',storageImg.uploadImages,storageImg.resizeImages,adminController.doaddNews)
router.post('/edit-news/:id',storageImg.uploadImages,storageImg.resizeImages,adminController.updateNews)
router.post('/search-date',adminController.searchDate)
router.post('/add-subcategory',adminController.addSubcategory)
router.post('/status-change',adminController.statusChange)
router.post('/un-delete-category/:id',adminController.undeleteCategory)
router.post('/delete-category/:id',adminController.deleteCategory)
router.post('/un-delete-subcategory/:id',adminController.undeletesubCategory)
router.post('/delete-subcategory/:id',adminController.deletesubCategory)
router.post('/un-delete-coupon/:id',adminController.undeleteCoupon)
router.post('/delete-coupon/:id',adminController.deleteCoupon)

module.exports = router