/* eslint-disable no-undef */
const express = require('express')
const router = express.Router();
const userController = require('../controller/user-controller')
const sessionController = require('../middllewares/session-control')

// GET METHODS

router.get('/',sessionController.userSession,userController.home)
router.get('/login',sessionController.userSession,userController.login)
router.get('/signup',sessionController.userSession,userController.signUp)
router.get('/otp',sessionController.userSession,userController.otp)
router.get('/email',sessionController.userSession,userController.email)
router.get('/reset',sessionController.userSession,userController.reset)
router.get('/logout',sessionController.userSession,userController.logOut)
router.get('/news/:id',sessionController.userSession,userController.news)
router.get('/profile',sessionController.userSession,userController.profile)
router.get('/editprofile/:id',sessionController.userSession,userController.editProfile)
router.get('/product-details/:id',sessionController.userSession,userController.details)
router.get('/profile-address',sessionController.userSession,userController.profileAddress)
router.get('/profile-orders',sessionController.userSession,userController.profileOrders)
router.get('/add-profile-address',sessionController.userSession,userController.addprofileAddress)
router.get('/cart',sessionController.userSession,userController.cart)
router.get('/plus-quantity/:id',sessionController.userSession,userController.plusQantity)
router.get('/minus-quantity/:id',sessionController.userSession,userController.minusQantity)
router.get('/delete-cart/:id',sessionController.userSession,userController.deleteCart)
router.get('/delete-all-cart/:id',sessionController.userSession,userController.deleteallCart)
router.get('/delete-wish/:id',sessionController.userSession,userController.deleteWishlist)
router.get('/wishlist',sessionController.userSession,userController.wishlist)
router.get('/shop',sessionController.userSession,userController.shop)
router.get('/shop/:id',sessionController.userSession,userController.category)
router.get('/checkout',sessionController.userSession,userController.checkout)
router.get('/add-address',sessionController.userSession,userController.address)
router.get('/cancel-order/:id',sessionController.userSession,userController.cancelOrder)
router.get('/order-success',sessionController.userSession,userController.orderSuccess)
router.get('/order-failed',sessionController.userSession,userController.orderFailed)

// POST METHODS

router.post('/login',userController.dologin)
router.post('/signup',userController.dosignUp)
router.post('/otp',userController.verifyOtp)
router.post('/resend',userController.resendOtp)
router.post('/reset-otp',userController.sendEmail)
router.post('/resend-reset-otp',userController.resetresendOtp)
router.post('/verify-reset-otp',userController.verifyresetOtp)
router.post('/reset',userController.resetPassword)
router.post('/updateProfile/:id',userController.updateProfile)
router.post('/profile-address',userController.doaddprofileAddress)
router.post('/search',userController.search)
router.post('/add-coupon/:id',userController.addCoupon)
router.post('/addtoCart/:id',userController.addCart)
router.post('/wishtoCart/:id',userController.wishtoCart)
router.post('/addtoWishlist/:id',userController.addWishlist)
router.post('/checkout',userController.doCheckout)
router.post('/add-address',userController.addAddress)
router.post('/verify-payment',userController.verifyPayment)
router.post('/order-products/:id',userController.orderProducts)

module.exports =router